version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:password@postgres:5432/myapp
    volumes:
      - .:/app
volumes:
  postgres_data:
